# Generated by Django 6.0.5 on 2026-05-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelTable(
            name='about',
            table='About',
        ),
    ]
