# Generated by Django 6.0.5 on 2026-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_links', '0002_alter_about_options_alter_about_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'links',
                'verbose_name_plural': 'links',
                'db_table': 'links',
            },
        ),
    ]
